export const POSTS_REQUESTED = 'POST_REQUESTED';
export const POSTS_RECEIVED = 'POST_RECEIVED';
export const POSTS_REJECTED = 'POST_REJECTED';
export const USER_REQUESTED = 'USER_REQUESTED';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const CHANGE_SEARCH = 'CHANGE_SEARCH';
